### ISSUE TITLE
[MASFRES-48] Duplicate plugin realm

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-apache-resources#67]
**[khaled baccouche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khbac)** opened **[MASFRES-48](https://issues.apache.org/jira/browse/MASFRES-48?redirect=false)** and commented

we build maven module B and it depends of another maven module A 

if we call goal of weblogic-maven-plugin in module A and in B we do the same thing but the plugin change version we got this Internal Error

**exception message :**

 

[main] ERROR org.apache.maven.cli.MavenCli - Internal error: java.lang.IllegalStateException: Duplicate plugin realm for plugin com.oracle.weblogic:weblogic-maven-plugin:12.2.1-0-0 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: Duplicate plugin realm for plugin com.oracle.weblogic:weblogic-maven-plugin:12.2.1-0-0
at org.apache.maven.lifecycle.internal.builder.BuilderCommon.handleBuildError(BuilderCommon.java:147)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:129)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalStateException: Duplicate plugin realm for plugin com.oracle.weblogic:weblogic-maven-plugin:12.2.1-0-0
at org.apache.maven.plugin.DefaultPluginRealmCache.put(DefaultPluginRealmCache.java:172)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:331)
at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:229)

---
No further details from [MASFRES-48](https://issues.apache.org/jira/browse/MASFRES-48?redirect=false)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Wrong project and not our plugin.

**Comment by jira-importer** [comment]
**[khaled baccouche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khbac)** commented

we have also the problem with one version of weblogic-maven-deploy.

if we omit option -U in call jenkins Artifactory plugin (which is calling also man) the pb disappear.

 

def rtMaven = Artifactory.newMavenBuild()def rtMaven = Artifactory.newMavenBuild() rtMaven.tool = MAVEN rtMaven.resolver server: server, releaseRepo: 'virtuel-maven-publication', snapshotRepo: 'virtuel-maven-dynamique' rtMaven.deployer server: server, releaseRepo: 'local-maven-publication-desjardins', snapshotRepo: 'local-maven-dynamique-desjardins'

rtMaven.run pom: 'pom.xml', goals: '--batch-mode -U -P serveur-assemblage,ic $EXTRA clean install', buildInfo: buildInfo

**Comment by jira-importer** [comment]
**[khaled baccouche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khbac)** commented

but I found this code which really throw the exception https://maven.apache.org/ref/3.3.9/maven-core/xref/org/apache/maven/plugin/DefaultPluginRealmCache.html and it belongs to pache maven

**Comment by jira-importer** [comment]
**[khaled baccouche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khbac)** commented

really when we see the exception it's clear that's an internal exception of maven. please reconsider your decision

**Comment by jira-importer** [comment]
Resolve #67
